repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
