/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttackDefenceExercise: typeof import('./components/pages/Simulation range/Role/AttackDefenceExercise.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    BriefLoopHoleController: typeof import('./components/pages/LoopHole/BriefLoopHoleController.vue')['default']
    Config: typeof import('./components/pages/SystemSettings/Config.vue')['default']
    Container: typeof import('./components/pages/Simulation range/Role/container.vue')['default']
    DetailedLoopHoleController: typeof import('./components/pages/LoopHole/DetailedLoopHoleController.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmulationRangeCheckboxGroup: typeof import('./components/pages/Simulation range/Role/EmulationRangeCheckboxGroup.vue')['default']
    Home: typeof import('./components/pages/Home.vue')['default']
    LoopHoleCard: typeof import('./components/pages/LoopHole/LoopHoleCard.vue')['default']
    LoopHoleController: typeof import('./components/pages/LoopHole/LoopHoleController.vue')['default']
    LoopHoleDig: typeof import('./components/pages/Simulation range/Role/LoopHoleDig.vue')['default']
    Mirror: typeof import('./components/pages/Simulation range/Role/Mirror.vue')['default']
    Range: typeof import('./components/pages/Simulation range/Role/range.vue')['default']
    Role: typeof import('./components/pages/SystemSettings/Role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationAwareness: typeof import('./components/pages/SituationAwareness/SituationAwareness.vue')['default']
    Task: typeof import('./components/pages/Simulation range/Role/Task.vue')['default']
    User: typeof import('./components/pages/SystemSettings/User.vue')['default']
  }
}
